apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankdefaultclassifier
  template:
    metadata:
      labels:
        app: bankdefaultclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/windy-collector-329105/mlops:v1
        ports:
        - containerPort: 5000